### PR TITLE
Test for lookAhead and bugfix

### PR DESCRIPTION
**Pull request by Hu3bl**
adds a unit test for the lookAhead method in SimpleLexer.
Additionally fixes a bug when lookAhead provides not the same tokes as next method.

### CODE REVIEW

**Comment by sherter** [comment]
@Hu3bl I was just about to submit my review, now it's to late :smile: 

I wanted to add that you should pass the Charset to `getBytes()` explicitly, in case someone uses a weird default system charset, say UTF-16 (is this even possible? I don't know, but make it explicit and we dont't have to worry about it :wink: )

**Comment by parttimenerd** [comment]
That's only the test. The lexer throws a LexerError if a character is > 127.

**Comment by sherter** [comment]
Then the test would be wrong... why wouldn't you want to fix bugs in tests?

**Comment by parttimenerd** [comment]
Good point. But, as you already mentioned, it shouldn't be of concern.

**Comment by Hu3bl** [comment]
I'm going to fix this @sherter. I will update it to bytes

**Pull request merged**
