### PR TITLE
Implement an on-the-fly register allocator

### PR DESCRIPTION
**Pull request by parttimenerd**
It reduces the runtime of programs in some benchmarks by one third.

### CODE REVIEW

**Comment by sherter** [comment]
I don't quite understand why you added the previously removed code back in? Most of it is still never used?!

**Comment by parttimenerd** [comment]
Can you please give some examples for your claim? Some methods might not be used, but most added methods should be used.

**Comment by sherter** [comment]
Maybe we should add an external tool that provides such information, if your IDE can't do that for you.
Examples in `CodeBlock` are:
- size()
- getAfterCompareInstructions()
- addAll()
- hasUnconditionalJump()
- getCompare() 
- getUnconditionalJump()
- getConditionalJumps()
- getBlockStartInstructions()

**Comment by parttimenerd** [comment]
My IDE can do that for me. I forgot to say that I remove some unused methods soon.
But I dislike the notion of removing all methods that aren't used currently. Especially if there's a non zero chance that they'll be used in the future (e.g. I use the `size` method in a new optimization I'm currently developing).

**Comment by sgraf812** [comment]
Well, I'd rather see them removed. Even if I'd need similar functionality in the future, I probably won't find it and just unintentionally duplicate stuff.

**Comment by parttimenerd** [comment]
Good point. I'll remove them soon.

**Comment by parttimenerd** [comment]
@sherter is code acceptable for you (I removed all the unused methods)?

**Comment by sherter** [comment]
The field `methodInfo`  in `AbstractRegAllocator` is also unused and `isUsedAfterInstruction(Instruction instruction)` in `Argument.InstructionRelations`. There are a few others but they might not be related to this PR...

**Comment by parttimenerd** [comment]
I use the `isUsedAfter` method in the optimization I'm currently developing.

**Comment by sherter** [comment]
okay then, ship it ;)  :+1:

**Pull request merged**
