### PR TITLE
Implemented Common Subexpression Elimination

### PR DESCRIPTION
**Pull request by sgraf812**

### CODE REVIEW

**Comment by sgraf812** [comment]
This fails because currently I don't respect dominance relations, e.g. if the exchanged subexpression is actually visible at the use site. I already have a solution in mind, but that's not gonna happen tonight.

**Comment by sgraf812** [comment]
Doing CSE might not always be beneficial, I think... Cheap expressions might not be worth to share, because they raise register pressure. But generally we should run with this.

**Comment by sherter** [comment]
You could use http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hash(java.lang.Object...) for hash calculation, otherwise :+1:

**Comment by sgraf812** [comment]
Thanks for the pointer, will do.

**Comment by sgraf812** [comment]
Something breaks CI, I'm not sure what. This is on hold until I figure it out.

Edit: Ah, it's just the old backend. So let's merge #110 first.

**Pull request merged**
