### PR TITLE
Inline until reaching a certain maximum of nodes in the graph

### PR DESCRIPTION
**Pull request by sherter**
We can always play with the actual MAX_SIZE. I'm interested in how this affects the runtime performance in speedcenter ;)

### CODE REVIEW

**Comment by sgraf812** [comment]
Hmm... I don't think we actually need different classes for this. The difference should more or less just be a flag. Stuff like the size limit is also useful for the `LeafInliner`, I think.

Edit: Also, as always, I dislike abstract classes. Why not extract an interface `InlineAbilityDecider` instead?

**Comment by sherter** [comment]
That was actually the approach I used at first but then discovered that I would need to modify the inlineCandidates() method, too. I couldn't find a way to do that cleanly, so I decided to just use inheritance... I know, you are not a fan of it (me neither), but it seemed to be the simplest solution.

**Comment by sherter** [comment]
I couldn't find a way to do that cleanly, so I decided to just use inheritance... I know, you are not a fan of it (me neither), but it seemed to be the simplest solution.

**Comment by sgraf812** [comment]
Because of the size limit? I think the `LeafInliner` should obey that limit, too. I was just too lazy to implement it in a correct way (like you did now)

**Comment by sherter** [comment]
I thought it would make sense to always inline leaf methods (with less than 1000 nodes), even if the overall size is bigger than the MAX_SIZE limit. Just a feeling, though....

**Comment by sgraf812** [comment]
That's really debatable, but I think the same arguments apply as for recursive functions: The call overhead is negligible in comparison.

Although if that would mean we can't inline a getter within a loop, that would be bad...

Anyway, I'd much rather see this implemented as a boolean flag. There is so much duplication of important logic (mainly the inlining heuristic) that I think we could tolerate the little ugliness that would bring.

**Pull request closed without merging**
